[package]
name = "tibba-config"
version = "0.1.0"
edition = "2024"

[lib]
name = "tibba_config"
path = "src/lib.rs"

[dependencies]
config = { workspace = true }
url = { workspace = true }
humantime = { workspace = true }
snafu = { workspace = true }
tibba-error = { path = "../tibba-error" }
