[package]
name = "tibba"
version = "0.1.0"
edition = "2024"

[dependencies]


[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"

[workspace]
members = [
    "tibba-config",
    "tibba-error",
    "tibba-hook",
    "tibba-util",
    "tibba-web",
]

[workspace.dependencies]
config = "0.15.9"
substring = "1.4.5"
once_cell = "1.20.3"
url = "2.5.4"
validator = { version = "0.20.0", features = ["derive"] }
humantime = "2.1.0"
dashmap = "6.1.0"
tracing = "0.1.41"
rust-embed = "8.6.0"
futures = "0.3.31"
snafu = "0.8.5"
axum = "0.8.1"
serde = { version = "1.0.218", features = ["derive"] }
tower = { version = "0.5.2", features = ["timeout"] }
uuid = { version = "1.15.1", features = ["v7"] }
nanoid = "0.4.0"
chrono = "0.4.40"
