[package]
name = "tibba"
version = "0.1.0"
edition = "2024"

[dependencies]


[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"

[workspace]
members = [
    "tibba-cache",
    "tibba-config",
    "tibba-crypto",
    "tibba-error",
    "tibba-hook",
    "tibba-middleware",
    "tibba-performance",
    "tibba-request",
    "tibba-router-common",
    "tibba-router-user",
    "tibba-state",
    "tibba-util",
    "tibba-validator",
    "tibba-web",
]

[workspace.dependencies]
config = "0.15.9"
substring = "1.4.5"
once_cell = "1.20.3"
url = "2.5.4"
validator = { version = "0.20.0", features = ["derive"] }
humantime = "2.1.0"
dashmap = "6.1.0"
tracing = "0.1.41"
rust-embed = "8.6.0"
futures = "0.3.31"
snafu = "0.8.5"
axum = "0.8.1"
serde = { version = "1.0.218", features = ["derive"] }
tower = { version = "0.5.2", features = ["timeout"] }
uuid = { version = "1.15.1", features = ["v7"] }
nanoid = "0.4.0"
chrono = "0.4.40"
lz4_flex = "0.11.3"
zstd = "0.13.3"
hex = "0.4.3"
hmac = "0.12.1"
sha2 = "0.10.8"
http-body-util = "0.1.2"
tokio = { version = "1.44.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }
axum-extra = { version = "0.10.0", features = ["cookie", "cookie-signed"] }
cookie = "0.18.1"
axum-client-ip = "0.7.0"
urlencoding = "2.1.3"
scopeguard = "1.2.0"
serde_json = "1.0.140"
reqwest = { version = "0.12.13", default-features = false, features = [
    "rustls-tls",
    "json",
] }
async-trait = "0.1.87"
bytes = "1.10.1"
deadpool-redis = { version = "0.20.0", features = ["cluster", "rt_tokio_1"] }
redis = { version = "0.29.1", features = ["tokio-comp", "aio"] }
lru = "0.13.0"
memory-stats = "1.2.0"
sysinfo = "0.33.1"
serde_urlencoded = "0.7.1"
os_info = "3.10.0"
serde_path_to_error = "0.1.17"
