[package]
name = "tibba"
version = "0.1.0"
edition = "2024"

[dependencies]


[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"

[workspace]
members = [
    "tibba-cache",
    "tibba-config",
    "tibba-crypto",
    "tibba-error",
    "tibba-hook",
    "tibba-middleware",
    "tibba-model",
    "tibba-opendal",
    "tibba-performance",
    "tibba-request",
    "tibba-router-common",
    "tibba-router-file",
    "tibba-router-user",
    "tibba-sql",
    "tibba-state",
    "tibba-util",
    "tibba-validator",
    "tibba-api",
    "tibba-scheduler",
    "tibba-session",
    "tibba-router-model",
]


[workspace.dependencies]
config = "0.15.11"
substring = "1.4.5"
once_cell = "1.21.3"
url = "2.5.4"
validator = { version = "0.20.0", features = ["derive"] }
humantime = "2.2.0"
dashmap = "6.1.0"
tracing = "0.1.41"
rust-embed = "8.7.0"
futures = "0.3.31"
snafu = "0.8.5"
axum = { version = "0.8.3", features = ["multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
tower = { version = "0.5.2", features = ["timeout"] }
uuid = { version = "1.16.0", features = ["v7"] }
nanoid = "0.4.0"
chrono = "0.4.40"
lz4_flex = "0.11.3"
zstd = "0.13.3"
hex = "0.4.3"
hmac = "0.12.1"
sha2 = "0.10.8"
http-body-util = "0.1.3"
tokio = { version = "1.44.2", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }
axum-extra = { version = "0.10.0", features = ["cookie", "cookie-signed"] }
cookie = "0.18.1"
axum-client-ip = "1.0.0"
urlencoding = "2.1.3"
scopeguard = "1.2.0"
serde_json = "1.0.140"
reqwest = { version = "0.12.15", default-features = false, features = [
    "rustls-tls",
    "json",
] }
async-trait = "0.1.88"
bytes = "1.10.1"
deadpool-redis = { version = "0.20.0", features = ["cluster", "rt_tokio_1"] }
redis = { version = "0.29.5", features = ["tokio-comp", "aio"] }
lru = "0.14.0"
memory-stats = "1.2.0"
sysinfo = "0.34.2"
serde_urlencoded = "0.7.1"
os_info = "3.10.0"
serde_path_to_error = "0.1.17"
time = { version = "0.3.41", features = ["serde"] }
derivative = "2.2.0"
captcha = "1.0.0"
sqlx = { version = "0.8.5", features = ["runtime-tokio", "mysql", "time"] }
base64 = "0.22.1"
opendal = { version = "0.53.1", features = [
    "services-mysql",
    "layers-mime-guess",
    "services-s3",
] }
tokio-cron-scheduler = { version = "0.13.0", features = ["signal"] }
mime_guess = "2.0.5"
image = "0.25.6"
http = "1.3.1"
