[package]
name = "tibba-scheduler"
version = "0.1.0"
edition = "2024"

[lib]
name = "tibba_scheduler"
path = "src/lib.rs"


[dependencies]
dashmap = { workspace = true }
once_cell = { workspace = true }
tibba-error = { path = "../tibba-error" }
tokio-cron-scheduler = { workspace = true }
tracing = { workspace = true }
