[package]
name = "tibba-hook"
version = "0.1.0"
edition = "2024"

[lib]
name = "tibba_hook"
path = "src/lib.rs"

[dependencies]
dashmap = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
tibba-error = { path = "../tibba-error" }
