[package]
name = "tibba-crypto"
version = "0.1.0"
edition = "2024"

[lib]
name = "tibba_crypto"
path = "src/lib.rs"

[dependencies]
snafu = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
tibba-error = { path = "../tibba-error" }
