[package]
name = "tibba-router-user"
version = "0.1.0"
edition = "2024"

[lib]
name = "tibba_router_user"
path = "src/lib.rs"


[dependencies]
axum = { workspace = true }
serde = { workspace = true }
validator = { workspace = true }
axum-extra = { workspace = true }
sqlx = { workspace = true }
tibba-error = { path = "../tibba-error" }
tibba-util = { path = "../tibba-util" }
tibba-middleware = { path = "../tibba-middleware" }
tibba-validator = { path = "../tibba-validator" }
tibba-cache = { path = "../tibba-cache" }
tibba-session = { path = "../tibba-session" }
tibba-model = { path = "../tibba-model" }
