[package]
name = "tibba-web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tibba-config = { path = "../tibba-config" }
tibba-error = { path = "../tibba-error" }
tibba-hook = { path = "../tibba-hook" }
tibba-util = { path = "../tibba-util" }
tibba-state = { path = "../tibba-state" }
tibba-middleware = { path = "../tibba-middleware" }
tibba-request = { path = "../tibba-request" }
tibba-router-common = { path = "../tibba-router-common" }
time = "0.3.39"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.19", features = ["local-time"] }
rust-embed = { workspace = true }
once_cell = { workspace = true }
tower = { workspace = true }
ctor = "0.4.0"

[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"
