[package]
name = "tibba-router-common"
version = "0.1.0"
edition = "2024"


[lib]
name = "tibba_router_common"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
os_info = { workspace = true }
humantime = { workspace = true }
captcha = { workspace = true }
base64 = { workspace = true }
validator = { workspace = true }
tibba-state = { path = "../tibba-state" }
tibba-error = { path = "../tibba-error" }
tibba-util = { path = "../tibba-util" }
tibba-cache = { path = "../tibba-cache" }
