//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use async_trait::async_trait;
use chrono::Utc;
use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(unique)]
    pub name: String,
    pub size: i64,
    pub content_type: String,
    #[sea_orm(column_type = "custom(\"mediumblob\")")]
    pub data: String,
    pub updater: Option<String>,
    pub creator: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModel {
    pub fn validate(&self) -> Result<(), DbErr> {
        if self.name.is_not_set() {
            return Err(DbErr::Custom("Name is required".to_string()));
        }
        if self.content_type.is_not_set() {
            return Err(DbErr::Custom("Content type is required".to_string()));
        }
        if self.data.is_not_set() {
            return Err(DbErr::Custom("Data is required".to_string()));
        }
        Ok(())
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C: ConnectionTrait>(
        mut self,
        _db: &C,
        insert: bool,
    ) -> Result<Self, DbErr> {
        if insert {
            self.validate()?;
            self.created_at = ActiveValue::set(Utc::now());
        }
        if let ActiveValue::Set(value) = &self.data {
            self.size = ActiveValue::set(value.len() as i64);
        }
        self.updated_at = ActiveValue::set(Utc::now());
        Ok(self)
    }
    async fn before_delete<C: ConnectionTrait>(self, _db: &C) -> Result<Self, DbErr> {
        // 禁止删除数据
        Err(DbErr::Custom("Delete is forbidden".to_string()))
    }
}
