//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use crate::error::HttpError;
use crate::util::{json_get_date_time, json_get_i64, json_get_string};
use async_trait::async_trait;
use chrono::{Duration, Utc};
use sea_orm::query::{Order, Select};
use sea_orm::{entity::prelude::*, ActiveValue, QueryOrder};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::ops::Add;
use substring::Substring;

pub type Result<T, E = HttpError> = std::result::Result<T, E>;

const ERROR_CATEGORY: &str = "entity_settings";

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub status: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(unique)]
    pub name: String,
    pub category: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub data: String,
    pub remark: String,
    pub started_at: DateTimeUtc,
    pub ended_at: DateTimeUtc,
    pub creator: String,
}

// fn order_by<C>(mut self, col: C, ord: Order) -> Self
// where
// C: IntoSimpleExpr,

pub fn order_by<E>(sql: Select<E>, orders: &str) -> Result<Select<E>>
where
    E: EntityTrait,
{
    if orders.is_empty() {
        return Ok(sql);
    }
    let mut s = sql;
    // TODO 是否有办法字符串转换为column
    for order in orders.split(',').into_iter() {
        let mut order_type = Order::Asc;
        let key = if order.starts_with('-') {
            order_type = Order::Desc;
            order.substring(1, order.len())
        } else {
            order
        };

        match key {
            "id" => s = s.order_by(Column::Id, order_type),
            "updated_at" => s = s.order_by(Column::UpdatedAt, order_type),
            "status" => s = s.order_by(Column::Status, order_type),
            _ => {
                let msg = format!("Order by {key} is unsupported");
                return Err(HttpError::new_with_category(&msg, ERROR_CATEGORY));
            }
        }
    }
    Ok(s)
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl ActiveModel {
    pub fn validate(&self) -> Result<(), DbErr> {
        if self.name.is_not_set() {
            return Err(DbErr::Custom("Name is required".to_string()));
        }
        if self.category.is_not_set() {
            return Err(DbErr::Custom("Category is required".to_string()));
        }
        if self.data.is_not_set() {
            return Err(DbErr::Custom("Data is required".to_string()));
        }
        if self.remark.is_not_set() {
            return Err(DbErr::Custom("Remark is required".to_string()));
        }
        Ok(())
    }
    pub fn from_value(value: Value) -> Result<Self> {
        let mut model = ActiveModel {
            ..Default::default()
        };
        if let Some(id) = json_get_i64(&value, "id")? {
            model.id = ActiveValue::set(id);
        }
        if let Some(status) = json_get_i64(&value, "status")? {
            model.status = ActiveValue::set(status as i8);
        }
        if let Some(name) = json_get_string(&value, "name")? {
            model.name = ActiveValue::set(name);
        }
        if let Some(category) = json_get_string(&value, "category")? {
            model.category = ActiveValue::set(category);
        }
        if let Some(data) = json_get_string(&value, "data")? {
            model.data = ActiveValue::set(data);
        }
        if let Some(remark) = json_get_string(&value, "remark")? {
            model.remark = ActiveValue::set(remark);
        }
        if let Some(started_at) = json_get_date_time(&value, "started_at")? {
            model.started_at = ActiveValue::set(started_at);
        }
        if let Some(ended_at) = json_get_date_time(&value, "ended_at")? {
            model.ended_at = ActiveValue::set(ended_at);
        }
        Ok(model)
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C: ConnectionTrait>(
        mut self,
        _db: &C,
        insert: bool,
    ) -> Result<Self, DbErr> {
        if insert {
            self.validate()?;
            self.created_at = ActiveValue::set(Utc::now());
            if self.started_at.is_not_set() {
                self.started_at = ActiveValue::set(Utc::now());
            }
            if self.ended_at.is_not_set() {
                self.ended_at = ActiveValue::set(Utc::now().add(Duration::days(365 * 10)));
            }
        }
        self.updated_at = ActiveValue::set(Utc::now());
        Ok(self)
    }
    async fn before_delete<C: ConnectionTrait>(self, _db: &C) -> Result<Self, DbErr> {
        // 禁止删除数据
        Err(DbErr::Custom("Delete is forbidden".to_string()))
    }
    async fn after_save<C: ConnectionTrait>(
        model: Model,
        _db: &C,
        _insert: bool,
    ) -> Result<Model, DbErr> {
        Ok(model)
    }
}
