[package]
name = "tibba-util"
version = "0.1.0"
edition = "2024"

[lib]
name = "tibba_util"
path = "src/lib.rs"

[dependencies]
snafu = { workspace = true }
uuid = { workspace = true }
nanoid = { workspace = true }
chrono = { workspace = true }
lz4_flex = { workspace = true }
zstd = { workspace = true }
axum = { workspace = true }
http-body-util = { workspace = true }
axum-extra = { workspace = true }
cookie = { workspace = true }
serde_json = { workspace = true }
tibba-error = { path = "../tibba-error" }

[dev-dependencies]
pretty_assertions = "1.4.1"
