# 需要注意配置仅支持两层级形式
basic:
  # 超时时间(秒)
  timeout: 60
  listen: 127.0.0.1:5000
  processing_limit: 1000

session:
  # 单位秒
  ttl: 604800

# 数据库配置
database:
  url: postgres://vicanso:A123456@127.0.0.1:5432/cybertect?max_connections=100