# 需要注意配置仅支持两层级形式
[basic]
# 超时时间(秒)
timeout = 60
listen = "127.0.0.1:5000"
processing_limit = 1_000
secret = "osbhdlycJ0"

[session]
cookie = "tibba"
# session有效期
ttl = "7d"

# 数据库配置
[database]
url = "mysql://vicanso:A123456@127.0.0.1:3306/tibba?max_connections=100"
