[package]
name = "tibba-state"
version = "0.1.0"
edition = "2024"
authors = ["Tree Xie <tree.xie@outlook.com>"]
license = "Apache-2.0"
homepage = "https://github.com/vicanso/tibba"
repository = "https://github.com/vicanso/tibba"
keywords = ["tibba", "state"]
description = "state for tibba"


[lib]
name = "tibba_state"
path = "src/lib.rs"

[dependencies]
arc-swap = { workspace = true }
tokio = { workspace = true }
