[package]
name = "tibba-error"
version = "0.1.0"
edition = "2024"

[lib]
name = "tibba_error"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
