# basic config
[basic]
# timeout for http request
timeout = 60
listen = "127.0.0.1:5000"
processing_limit = 1_000
secret = "osbhdlycJ0"
prefix = "/api"


# session config
[session]
# session cookie name
cookie = "tibba_web"
# session ttl
ttl = "7d"

[opendal]
url = "http://n150:9000?bucket=tibba-web&region=default&access_key_id=bpAx0XyPVwvcpiqI6btK&secret_access_key=R45iLopZQmAbl4bvuErQxS9yRhwVux5aQv1beCX9"
