[package]
name = "tibba-middleware"
version = "0.1.0"
edition = "2024"


[lib]
name = "tibba_middleware"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
tibba-state = { path = "../tibba-state" }
tibba-error = { path = "../tibba-error" }
