[package]
name = "tibba-middleware"
version = "0.1.0"
edition = "2024"


[lib]
name = "tibba_middleware"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true }
axum-client-ip = { workspace = true }
urlencoding = { workspace = true }
tracing = { workspace = true }
snafu = { workspace = true }
scopeguard = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
cookie = { workspace = true }
time = { workspace = true }
derivative = { workspace = true }
tibba-state = { path = "../tibba-state" }
tibba-error = { path = "../tibba-error" }
tibba-util = { path = "../tibba-util" }
tibba-cache = { path = "../tibba-cache" }
