[package]
name = "tibba-sql"
version = "0.1.0"
edition = "2024"

[lib]
name = "tibba_sql"
path = "src/lib.rs"

[dependencies]
snafu = { workspace = true }
sqlx = { workspace = true }
tibba-config = { path = "../tibba-config" }
tibba-error = { path = "../tibba-error" }
tracing = { workspace = true }
url = { workspace = true }
validator = { workspace = true }
