CREATE TABLE `http_detectors` (
  `id` BIGINT unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `status` TINYINT NOT NULL DEFAULT '0' COMMENT '状态，0：禁用，1：启用',
  `name` VARCHAR(255) NOT NULL COMMENT '名称',
  `interval` SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '间隔时间，单位：分钟',
  `url` TEXT NOT NULL COMMENT 'URL',
  `method` VARCHAR(10) NOT NULL DEFAULT 'GET' COMMENT 'HTTP方法',
  `alpn_protocols` JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT 'ALPN协议',
  `resolves` JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT 'DNS解析',
  `headers` JSON NOT NULL DEFAULT (JSON_OBJECT()) COMMENT 'HTTP头',
  `ip_version` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'IP版本',
  `skip_verify` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否跳过证书验证',
  `dns_servers` JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT 'DNS服务器',
  `body` BLOB COMMENT '请求体',
  `script` TEXT COMMENT '脚本',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` BIGINT unsigned NOT NULL COMMENT '创建人',
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `idx_deleted_at` (`deleted_at`) COMMENT '软删除索引',
  UNIQUE KEY `name` (`name`, `deleted_at`) COMMENT '名称唯一索引（仅对未删除记录生效）'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT="http_detectors表";
