CREATE TABLE `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL DEFAULT '0' COMMENT '状态，0：禁用，1：启用',
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `account` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `roles` JSON DEFAULT NULL COMMENT '用户角色',
  `groups` JSON DEFAULT NULL COMMENT '用户群组',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `email` VARCHAR(255) DEFAULT NULL COMMENT '用户邮箱',
  `avatar` VARCHAR(1024) DEFAULT NULL COMMENT '用户头像',
  PRIMARY KEY (`id`) COMMENT '主键',
  UNIQUE KEY `user_account` (`account`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
