CREATE TABLE `http_stats` (
  `id` BIGINT unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `target_id` BIGINT unsigned NOT NULL COMMENT '目标ID',
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '软删除时间',
  `url` TEXT NOT NULL COMMENT 'URL',
  `dns_lookup` INT COMMENT 'DNS查询时间',
  `quic_connect` INT COMMENT 'QUIC连接时间',
  `tcp_connection` INT COMMENT 'TCP连接时间',
  `tls_handshake` INT COMMENT 'TLS握手时间',
  `server_processing` INT COMMENT '服务器处理时间',
  `content_transfer` INT COMMENT '内容传输时间',
  `total` INT COMMENT '总时间',
  `addr` VARCHAR(255) COMMENT '地址',
  `status` INT COMMENT '状态码',
  `tls` VARCHAR(20) COMMENT 'TLS版本',
  `alpn` VARCHAR(10) COMMENT 'ALPN',
  `subject` VARCHAR(1000) COMMENT '证书主题',
  `issuer` VARCHAR(1000) COMMENT '证书颁发者',
  `cert_not_before` DATETIME COMMENT '证书有效期开始时间',
  `cert_not_after` DATETIME COMMENT '证书有效期结束时间',
  `cert_cipher` VARCHAR(50) COMMENT '证书加密套件',
  `cert_domains` JSON COMMENT '证书域名',
  `body` BLOB COMMENT '响应体',
  `body_size` INT COMMENT '响应体大小',
  `headers` JSON COMMENT '响应头',
  `error` TEXT COMMENT '错误信息',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `idx_deleted_at` (`deleted_at`) COMMENT '软删除索引',
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT="http_stats表";
