CREATE TABLE `web_page_detectors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `status` TINYINT NOT NULL DEFAULT '0' COMMENT '状态，0：禁用，1：启用',
  `name` VARCHAR(255) NOT NULL COMMENT '名称',
  `interval` SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '间隔时间，单位：分钟',
  `url` TEXT NOT NULL COMMENT 'URL',
  `width` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '宽度',
  `height` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '高度',
  `user_agent` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户代理',
  `accept_language` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接受语言',
  `platform` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '平台',
  `wait_for_element` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '等待元素',
  `device_scale_factor` FLOAT NOT NULL DEFAULT 0 COMMENT '设备缩放因子',
  `timeout` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '超时时间，单位：秒',
  `capture_screenshot` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否捕获截图',
  `capture_element` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '捕获元素',
  `remark` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '备注',
  `regions` JSON NOT NULL DEFAULT (JSON_ARRAY()) COMMENT '触发区域',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`) COMMENT '主键',
  KEY `idx_deleted_at` (`deleted_at`) COMMENT '软删除索引',
  UNIQUE KEY `name` (`name`, `deleted_at`) COMMENT '名称唯一索引（仅对未删除记录生效）'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT="web_page_detectors表";