name: "publish"
on:
  push:
    # tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always
  IMAGE_NAME: vicanso/tibba

jobs:
  build:
    timeout-minutes: 3600
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - { arch: "linux/amd64", tag: "amd64", runs-on: "ubuntu-22.04" }
          - { arch: "linux/arm64", tag: "arm64", runs-on: "ubuntu-22.04-arm" }
    steps:
      - name: Change Swap Space
        run: |
          swapon --show=NAME | tail -n 1
          df -lh
          export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
          sudo swapoff $SWAP_FILE
          sudo rm $SWAP_FILE
          export SWAP_FILE=/swapfile
          sudo fallocate -l 16G $SWAP_FILE
          sudo chmod 600 $SWAP_FILE
          sudo mkswap $SWAP_FILE
          sudo swapon $SWAP_FILE
      - name: Swap space report after modification
        shell: bash
        run: |
          echo "Memory and swap:"
          free -h
          echo
          swapon --show
          df -lh
          echo
          arch
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: |
      #       vicanso/tibba
      #     tags: |
      #       type=raw,value=latest
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform.arch }}
          build-args: |
            GIT_COMMIT_ID=${{ github.sha }}
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.platform.tag }}
          push: true
      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
  merge:
    runs-on: ubuntu-22.04
    needs: [build] # 等待所有架构构建完成
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ${{ env.IMAGE_NAME }}:latest \
            ${{ env.IMAGE_NAME }}:amd64 \
            ${{ env.IMAGE_NAME }}:arm64